# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='like',
            field=models.ManyToManyField(related_name='like', to='login.User'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='login.User'),
        ),
    ]
